-
  branches:
      only:
        - master
        - /release\/.*/
  version: 2.0.{build}
  image: Previous Visual Studio 2017
  environment:
    NUGET_SOURCE: https://www.nuget.org/api/v2/package
    NUGET_APIKEY:
      secure: 1jnqj8cWDyjRGRpMrJipQMRQj/WE79/u1aqv6uXRDRxzmfbEQaOTrLqKMVpQK+Hd
  build_script:
  - ps: .\build.ps1
  test: off
  cache:
  - packages -> **\packages.config
-
  branches:
      only:
        - develop
  version: 2.0.{build}
  image: Previous Visual Studio 2017
  environment:
    NUGET_SOURCE: https://www.myget.org/F/mvvmcross/api/v2/package
    NUGET_APIKEY:
      secure: 0PNC9eZWAinI1KkE9usbhPAwF1wudL5GJi6lJn9Ylb67M7SE17LIXBoMHuRKJaLE
  build_script:
  - ps: .\build.ps1
  test: off
  cache:
  - packages -> **\packages.config